const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createHubServer } = require('../cloud/server');
const { RemoteAgent, request } = require('../lib/remote-agent');
const { Hub } = require('../cloud/service');
const fractal = require('../lib/fractal');
const sleep = ms => new Promise(r => setTimeout(r,ms));
async function main() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(),'compute-bridge-market-test-'));
  const file = path.join(dir,'hub.sqlite'); let now = Date.now();
  let app = createHubServer({file,clock:()=>now}); let agent;
  await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
  const base='http://127.0.0.1:'+app.server.address().port;
  const api=(token,route,method='POST',data={})=>request(base,token,'/v1/'+route,method,method==='GET'?undefined:data);
  try {
    assert.throws(()=>new Hub({file}),/folosită/);
    const users=[];
    for(const name of ['alice','bob','carol']) {
      const auth=await api('','auth/register','POST',{email:name+'@example.com',password:'test-password-123',name});
      const state=await api(auth.token,'state','GET');assert.equal(state.user.credits,100);
      assert.equal(state.parties,undefined);assert.equal(state.invites,undefined);
      users.push({token:auth.token,id:state.user.id});
    }
    const [a,b,c]=users;
    await assert.rejects(api('','state','GET'),e=>e.status===401);
    await assert.rejects(api(a.token,'parties'),e=>e.status===404);
    await assert.rejects(api('','auth/register','POST',{email:'alice@example.com',password:'test-password-123'}),e=>e.status===409);
    const logged=await api('','auth/login','POST',{email:'alice@example.com',password:'test-password-123'});
    assert.equal((await api(logged.token,'state','GET')).user.credits,100,'login cannot mint credits');
    const config={name:'Seller',slots:2,cpuPercent:75,ramGb:4,vramGb:0,gpuRender:false,until:now+3600000,price:1,market:true,commitment:'reserved'};
    await assert.rejects(api(b.token,'devices','POST',{...config,slots:0,clientKey:crypto.randomBytes(32).toString('hex')}),e=>e.status===400);
    const register=(u,extra={})=>api(u.token,'devices','POST',{...config,clientKey:crypto.randomBytes(32).toString('hex'),...extra});
    const da=await register(a,{market:false});const db=await register(b);
    assert.equal((await api(a.token,'state','GET')).devices.some(d=>d.id===db.id),false,'registration is not an active offer');
    const body={execution:'remote',requestDeviceId:da.id,providerId:db.id,mode:'fractal',width:200,height:200,iterations:100,minRam:2,budget:5};
    await assert.rejects(api(a.token,'jobs','POST',body),e=>e.status===400);
    agent=new RemoteAgent({server:base,token:db.token,config});await agent.start();
    assert.ok((await api(a.token,'state','GET')).devices.find(d=>d.id===db.id)?.online,'offer needs real heartbeat, no approval step');
    await assert.rejects(api(a.token,'jobs','POST',{...body,minRam:8}),e=>e.status===400);
    await assert.rejects(api(a.token,'jobs','POST',{...body,mode:'blender',samples:8,frames:2,minVram:4}),e=>e.status===400);
    assert.equal(app.hub.user(a.id).balance,100000,'failed compatibility cannot debit credits');
    const rendered=await api(a.token,'jobs','POST',body);
    for(let i=0;i<160;i++){if(app.hub.s.jobs.find(j=>j.id===rendered.id).status==='done')break;await sleep(100);}
    const done=app.hub.s.jobs.find(j=>j.id===rendered.id);assert.equal(done.status,'done',agent.message);
    assert.ok(done.spent>0);assert.equal(app.hub.user(a.id).balance,100000-done.spent);assert.equal(app.hub.user(b.id).balance,100000+done.spent);
    assert.ok(done.tasks.every(t=>t.deviceId===db.id),'selected provider computes every task');
    const image=await fetch(base+'/v1/jobs/'+done.id+'/image',{headers:{authorization:'Bearer '+a.token}});assert.equal(image.status,200);assert.equal(Buffer.from(await image.arrayBuffer()).readUInt32BE(16),200);
    assert.equal((await fetch(base+'/v1/jobs/'+done.id+'/image',{headers:{authorization:'Bearer '+c.token}})).status,404);
    await agent.stop();agent=null;
    assert.equal((await api(a.token,'state','GET')).devices.some(d=>d.id===db.id),false,'stopped provider disappears immediately');
    console.log('PASS: 100 welcome credits once, no group routes, real offered agent, selected PC CPU render, buyer debit/seller income, private image and stopped-offer removal');

    const seller=await register(b,{slots:1});await api(seller.token,'agent/heartbeat');
    const other=await register(c,{price:20});await api(other.token,'agent/heartbeat');
    const jId=(await api(a.token,'jobs','POST',{...body,providerId:seller.id,budget:2})).id;
    assert.equal((await api(other.token,'agent/task?kind=cpu','GET')).task,null,'other PC cannot steal selected work');
    const task=(await api(seller.token,'agent/task?kind=cpu','GET')).task;assert.ok(task);
    assert.equal((await api(seller.token,'agent/task?kind=cpu','GET')).task,null,'slot capacity enforced');
    await assert.rejects(api(other.token,'agent/result','POST',task),e=>e.status===409);
    await assert.rejects(api(seller.token,'agent/result','POST',{...task,pixels:Buffer.alloc(task.width*task.rows*3,255).toString('base64')}),e=>e.status===400);
    const result={...task,pixels:fractal.renderTile(task).toString('base64'),durationMs:999999999};
    await Promise.all([api(seller.token,'agent/result','POST',result),api(seller.token,'agent/result','POST',result)]);
    assert.equal(app.hub.s.ledger.filter(l=>l.ref===task.taskId&&l.reason==='Sarcină acceptată').length,1);
    const interrupted=(await api(seller.token,'agent/task?kind=cpu','GET')).task;
    const paid=app.hub.s.jobs.find(j=>j.id===jId);const bond=paid.tasks.find(t=>t.id===interrupted.taskId).bond;const balance=app.hub.user(a.id).balance;
    now+=61000;await api(other.token,'agent/heartbeat');assert.equal(app.hub.user(a.id).balance,balance+bond);
    await assert.rejects(api(seller.token,'agent/result','POST',{...interrupted,pixels:result.pixels}),e=>e.status===409);
    await api(a.token,'jobs/cancel','POST',{jobId:jId});assert.equal(paid.escrow,0);
    assert.equal(app.hub.s.users.reduce((n,u)=>n+u.balance,0),300000,'credit transfers conserved');
    console.log('PASS: selected PC isolation, capacity, forged results, duplicate payment, offline reassignment, stale leases and cancellation refund');

    await api(seller.token,'agent/heartbeat');
    const limited=(await api(a.token,'jobs','POST',{...body,providerId:seller.id,width:640,height:360,iterations:1000,budget:1.1})).id;
    const first=(await api(seller.token,'agent/task?kind=cpu','GET')).task;
    await api(seller.token,'agent/result','POST',{...first,pixels:fractal.renderTile(first).toString('base64')});
    assert.equal((await api(seller.token,'agent/task?kind=cpu','GET')).task,null);
    assert.match(app.hub.state(a.id).jobs.find(j=>j.id===limited).waiting,/Bugetul/);
    await assert.rejects(api(c.token,'jobs/budget','POST',{jobId:limited,amount:5}),e=>e.status===404);
    await api(a.token,'jobs/budget','POST',{jobId:limited,amount:5});
    const draining=(await api(seller.token,'agent/task?kind=cpu','GET')).task;assert.ok(draining);
    await api(seller.token,'agent/stop','POST',{force:false});assert.equal((await api(seller.token,'agent/task?kind=cpu','GET')).task,null);
    await api(seller.token,'agent/result','POST',{...draining,pixels:fractal.renderTile(draining).toString('base64')});
    await api(a.token,'jobs/cancel','POST',{jobId:limited});
    const forcedSeller=await register(b,{slots:1});await api(forcedSeller.token,'agent/heartbeat');
    const forcedId=(await api(a.token,'jobs','POST',{...body,providerId:forcedSeller.id})).id;
    const forced=(await api(forcedSeller.token,'agent/task?kind=cpu','GET')).task;
    const forcedBond=app.hub.s.jobs.find(j=>j.id===forcedId).tasks.find(t=>t.id===forced.taskId).bond;
    const beforeForce=app.hub.user(a.id).balance;
    await api(forcedSeller.token,'agent/stop','POST',{force:true});assert.equal(app.hub.user(a.id).balance,beforeForce+forcedBond);
    await api(a.token,'jobs/cancel','POST',{jobId:forcedId});
    const recover=await register(b,{slots:1});await api(recover.token,'agent/heartbeat');
    const restartId=(await api(a.token,'jobs','POST',{...body,providerId:recover.id})).id;
    const lease=(await api(recover.token,'agent/task?kind=cpu','GET')).task;const held=app.hub.s.jobs.find(j=>j.id===restartId).tasks.find(t=>t.id===lease.taskId).bond;
    const balances=app.hub.s.users.map(u=>u.balance);balances[1]+=held;
    await app.close();app=null;
    const restarted=new Hub({file,clock:()=>now});assert.deepEqual(restarted.s.users.map(u=>u.balance),balances);
    assert.ok(restarted.store.get(task.taskId));assert.equal(restarted.s.jobs.flatMap(j=>j.tasks).filter(t=>t.status==='assigned').length,0);
    assert.equal(restarted.s.ledger.filter(l=>l.ref==='signup').length,3);restarted.close();
    console.log('PASS: budget top-up, graceful drain, persisted balances and results, restart releases bonds without repeating welcome credits');
    const legacyFile=path.join(dir,'old.sqlite');const { Store }=require('../cloud/store');const old=new Store(legacyFile);
    old.transaction(s=>{s.users.push({id:'old-user',name:'Old user',email:'old@example.com',balance:0});s.parties=[{id:'old-group',members:['old-user']}];s.invites=[{}];});old.close();
    const migrated=new Hub({file:legacyFile});assert.equal(migrated.user('old-user').balance,100000);assert.equal(migrated.s.parties,undefined);assert.equal(migrated.s.invites,undefined);migrated.close();
    const again=new Hub({file:legacyFile});assert.equal(again.user('old-user').balance,100000);again.close();
    console.log('PASS: existing zero-credit account gets one welcome grant, obsolete group settings removed, no second grant after restart');
  } finally {
    await agent?.stop();if(app)await app.close();
    if(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep))fs.rmSync(dir,{recursive:true,force:true});
  }
}
main().catch(e=>{console.error(e);process.exitCode=1});
